-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3gRtOOMM86ZiycFt
EGLLO4s3uHTmfn5S6OAcGM2MZyygCgYIKoZIzj0DAQehRANCAATnV/UeJumQ6xk5
mNDjyRmDLtUZrtslsK9iB67J3JTz1iVQI+0iSBmUWAW/oRkJylJqrvrPr0/FABHK
LXQN1Y1G
-----END PRIVATE KEY-----